### ISSUE TITLE
Created east-couchbase adapter

### ISSUE THREAD

**Issue by ramiel** [okv/east#10]
I created an adapter for couchbase.
It works but for the moment there are no tests and documentation. I'll add hem soon. BTW if you want to have a look it's at
https://www.npmjs.com/package/east-couchbase

**Comment by okv** [comment]
Hi.
Nice work in general.

For get better driver compatibility with dependencies of an application (e.g. when using east for migrating db of web app which already works with that db) at which east will be used we are using `peerDependencies` for the driver we also try to use wider (as much as possible) versions range e.g. ["mongodb": ">=2.0.0"](https://github.com/okv/east-mongo/blob/master/package.json#L20) for same reason - to encourage npm to install single driver for app and east.

You can test your adapter using east [tests](https://github.com/okv/east#creating-and-testing-own-adapter). But some adapter specific tests are also good idea.

It will be nice if you specify nodejs version requirements for your adapter because you are using es6 syntax and it will not work in old version of node. It's also good to have some documentation =)

**Comment by ramiel** [comment]
Yes, good points.
For the driver, I'll add a (permissive) peer-dependency.
For the tests: I've already tested the adapter against east test suite and I plan to add specific ones.
For the documentation: of course it needs to be added :)

I'll do all of this stuff during the next week.

**Comment by ramiel** [comment]
Ah, I'm planning also to move the implementation to not use es6 syntax. This came from the fact I actually implemented the adapter for another project where we're using es6 syntax but there is no special needs here and so I can use "older" javascript

**Comment by okv** [comment]
Glad to hear all that. Please let me know when documentation will be ready - I will add link to your adapter from east page.

**Comment by ramiel** [comment]
I think a first fully usable version is ready.
I added a minimal test suite (to be improved) and the adapter pass your test suite.
The project is now documented and I removed all the es6 syntax

**Comment by okv** [comment]
That's great, I'll add a link and close the issue.
p.s. One thing about docs - it will be nice if you will provide info about which couch driver you're using and about exposing it as `client.db`.

**Comment by ramiel** [comment]
Hey, look that `couchbase` and `couchbd` are not the same thing, maybe you should rename it in the documentation ;)

**Comment by okv** [comment]
oops, you're right =) fixed, thanks
