### ISSUE TITLE
Bump version of underscore

### ISSUE THREAD

**Issue by himeno61** [okv/east#107]
Currently in project version 1.13.6 is used for `underscore`. 
However, it is prone to CVE-2021-23358 vulnerability: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-23358

> The package 'underscore' from 1.13.0-0 and before 1.13.0-2, from 1.3.2
and before 1.12.1 are vulnerable to Arbitrary Code Execution via the
template function, particularly when a variable property is passed as
an argument as it is not sanitized.

Would it be possible to bump up this version?

**Comment by okv** [comment]
Hi @himeno61, sorry for the late reply. Currently, `underscore@1.12.1` has been used and it seems like according to the `npm audit` check there is no prod related vulnerabilities:

```shell
> node --version
v20.18.0
> npm ci
> npm ls underscore
east@2.0.3
└── underscore@1.12.1

> npm audit --omit=dev
found 0 vulnerabilities
```

Since the latest version of east (`2.0.3`) doesn't seem to have that problem, I'm going to close this issue but please let me know if you have any other questions.
