### ISSUE TITLE
I would like to have the ability to block rollbacks in production unless --force is applied

### ISSUE THREAD

**Issue by justinmchase** [okv/east#18]
I have a custom adapter and essentially I have a stage in an environment variable:
```
proccess.env.STAGE === 'prod'
```

I would like to abort rollbacks in prod unless `--force` is specified. I can think of a couple of ways to do this but the simplest might be to just add the `command` and `force` values onto the `params` object sent into the Adapter constructor.

e.g., my adapter may look like this:
```js
function Adapter (params) {
  this.params = params || {}
}

Adapter.prototype.connect = function (callback) {
  if (process.env.STAGE === 'prod' &&
    this.params.command === 'rollback' &&
    !this.params.force) {

    return callback(new Error(
      `Unable to rollback in production. ` +
      `Use --force if you're sure you want to rollback`))

  }

  // ...
}
```

**Comment by okv** [comment]
Currently adapters layer is not aware of current command and think it's good to have layers with specified responsibilities.
To implement such custom case (prevent rollback on production without --force) I would do it outside of east - e.g. in some wrapper which executes east or inside every rollback function by checking STAGE and another env variable instead of --force or something like that)

**Comment by justinmchase** [comment]
I basically just parsed argv myself inside of the adapter constructor, I just wanted a fallback here. I do have protection in scripts that call east but its possible to run it manually and I wanted to make sure nobody is doing that accidentally.
